module.exports = {
  mode: 'jit',  
  content: ["./src/*.html"],
  darkMode: 'class',
  theme: {
    boxShadow: {
      DEFAULT: '0 2px 15px rgb(0 0 0 / 10%)',
      header: '0 1px 1px 0 rgb(0 0 0 / 20%)',
      img:'0 4px 8px 0 rgb(0 0 0 / 20%)',
      select:'0 0 0 1px transparent',
      tableShadow: '0 0 3px #e5e5e5',
      loadmore:'0 1px 2px 0 rgb(0 0 0 / 5%)',
      btnActive:'0 0 0 0.25rem rgb(25 135 84 / 50%)',
      applyJob:'0 6px 15px rgb(36 37 38 / 8%)',
  },
  backgroundPosition: {
    bgLeft10: '10px',
    bgLeft0: '0px',
  },
    extend: {
      keyframes: {
        ripple: {
          '0%': { 'box-shadow': '0 0 0 0 rgba(0, 0, 0, 0.1)' },
          '100%': { 'box-shadow': '0 0 0 50px rgba(0, 0, 0, 0)' }, 
        }
    }, 
    animation: {
        ripple: 'ripple 2s ease-in-out infinite',
        customPulse: 'ping 3s ease-out infinite',
        colorSwap: 'spin 4s linear infinite',
    },
      screens: {
        'media-min-w-md': {'min': '992px'},      
        'media-max-w-xs': {'max': '639.98px'},   
        'media-max-w-sm': {'max': '767.98px'},   
        'media-max-w-md': {'max': '991.98px'},      
        'media-max-w-lg': {'max': '1199.98px'},      
      },     
      spacing: {
        '15': '3.75rem', 
      },       
      colors: {
        //body:'var(--color-body)', 
        body:'#f7f7f7',
        errorPage:'rgba(255, 155, 68, 0.2)',
        chatBubble:'#f2f2f2',
        link:'#333333',
        select:'#e3e3e3',
        favourite:'#ffd200',
        blackOverlay:'rgba(0,0,0,0.2)', 
        fileUploadbg:'rgba(33,33,33,0.5)', 
        dashboardIconOverlay:'var(--color-dashboardIconOverlay)', 
        dashboardIconOverlay2:'rgba(242, 17, 54,0.12)',
        dashboardIconOverlay3: 'rgba(15, 183, 107,0.12)',
        dashboardIconOverlay4: 'rgba(255, 152, 0,0.12)',
        dashboardIconOverlay5: 'rgba(2, 182, 179,0.12)',
        dashboardIconOverlay6: 'rgba(108, 97, 246, .2)',
        listbg:'rgba(33, 33, 33, 0.05)',
        btnBorder:'#cccccc',
        cardBorder:'#ededed',
        cardBorderDark:'#e5e5e5',
        muted:'#8e8e8e',
        primary: 'var(--color-primary)',
        secondary: '#6c757d',
        info: '#009efb',
        orange:'#fe8259',
        warning:'#f39c12',
        success:'#55ce63',
        success1:'#26af48',
        light:'#f8f9fa',
        successHover:'#4ab657',
        danger:'#f62d51',
        searchbg: 'rgba(255,255,255,0.1)',
        btnControls: 'rgba(255,255,255,0.2)',
        whiteOpacity:'rgba(255,255,255,0.7)',
        scrollbar:'rgba(204,204,204,0.5)',
        countBubble: '#7460ee',
        dark:'#212529',
        blackOpacity:'rgba(0,0,0,0.2)',
        dropdownBorder: 'rgba(0,0,0,0.2)',
        chatTimestamp: 'rgba(0,0,0,0.5)',
        proileEditoverlay: 'rgba(0,0,0,0.3)',
        blackHoverbg: 'rgba(0,0,0,0.5)',
        chatPlaceholder: 'rgba(69, 81, 97, 0.6)',
        seperator:'rgba(0,0,0,0.15)',
        dropDown:'rgba(0,0,0,0.1)',
        dropdownColor:'#1e2125',
        dropdownhoverColor:'#e9ecef',
        dropdownBorderBtm:'#eeeeee',
        notiDetails:'#989c9e',
        notiTitle:'#333333',
        notiTime:'#bdbdbd',
        sidebar:'#34444c',
        sidebarTitle:'#ebecf1',
        sidebarText:'#b7c0cd',
        statusOnline:'#55ce63',
        statusAway:'#faa937',
        pageTitle:'#1f1f1f',
        addbtnHover:'#ff851a',
        tableStripe:'#EAEAEA',
        warning1:'#ffbc34',
        tablePrimary:'#cfe2ff',
        tableSecondary:'#e2e3e5',
        tableSuccess:'#d1e7dd',
        tableDanger:'#f8d7da',
        tableWarning:'#fff3cd',
        tableInfo:'#cff4fc',
        tableLight:'#f8f9fa',
        tableDark:'#212529',
        pagination:'#dee2e6',
        alertPrimary: {
          fontColor: '#084298',
          bgColor: '#cfe2ff',
          borderColor: '#b6d4fe',
        },
        alertSecondary: {
          fontColor: '#41464b',
          bgColor: '#e2e3e5',
          borderColor: '#d3d6d8',
        },
        alertWarning: {
          fontColor: '#664d03',
          bgColor: '#fff3cd',
          borderColor: '#ffecb5',
        },
        alertDanger: {
          fontColor: '#842029',
          bgColor: '#f8d7da',
          borderColor: '#f5c2c7',
        },
        alertSuccess: {
          fontColor: '#0f5132',
          bgColor: '#d1e7dd',
          borderColor: '#badbcc',
        },
        alertInfo: {
          fontColor: '#055160',
          bgColor: '#cff4fc',
          borderColor: '#b6effb',
        },
        alertLight: {
          fontColor: '#636464',
          bgColor: '#fefefe',
          borderColor: '#fdfdfe',
        },
        alertDark: {
          fontColor: '#141619',
          bgColor: '#d3d3d4',
          borderColor: '#bcbebf',
        },
        btnPrimary: {
          fontColor: '#ffffff',
          bgColor: '#ff9b44',
          borderColor: '#ff9b44',
          hoverbgColor: '#ff851a',
          hoverborderColor: '#ff851a',
        },
        btnSecondary: {
          fontColor: '#ffffff',
          bgColor: '#6c757d',
          borderColor: '#6c757d',
          hoverbgColor: '#5c636a',
          hoverborderColor: '#5c636a',
        },
        btnSuccess: {
          fontColor: '#ffffff',
          bgColor: '#55ce63',
          borderColor: '#55ce63',
          hoverbgColor: '#4ab657',
          hoverborderColor: '#4ab657',
        },
        btnDanger: {
          fontColor: '#ffffff',
          bgColor: '#f62d51',
          borderColor: '#f62d51',
          hoverbgColor: '#e6294b',
          hoverborderColor: '#e6294b',
        },
        btnWarning: {
          fontColor: '#000000',
          bgColor: '#ffbc34',
          borderColor: '#ffbc34',
          hoverbgColor: '#e9ab2e',
          hoverborderColor: '#e9ab2e',
        },
        btnInfo: {
          fontColor: '#000000',
          bgColor: '#009efb',
          borderColor: '#009efb',
          hoverbgColor: '#028ee1',
          hoverborderColor: '#028ee1',
        },
        btnLight: {
          fontColor: '#000000',
          bgColor: '#f8f9fa',
          borderColor: '#f8f9fa',
          hoverbgColor: '#f9fafb',
          hoverborderColor: '#f9fafb',
        },
        btnDark: {
          fontColor: '#ffffff',
          bgColor: '#212529',
          borderColor: '#212529',
          hoverbgColor: '#1c1f23',
          hoverborderColor: '#1c1f23',
        },
        btnLink: {
          fontColor: '#333333',
          hoverfontColor: '#0a58ca',
        },
        pink: {
          light: '#ff7ce5',
          DEFAULT: '#ff49db',
          dark: '#ff16d1',
        },
        swapBody: '#23272b',
        swapText: '#bbc4cc',
        swapBg:'#16191c',
        swapBgBlack:'#000000',
        swapInput:'#2e3439',
        swapTable:'#212529',
        swapBorderPrimary:'#2e3840'
      },
      fontFamily: {
        CircularStd: ['CircularStd', 'sans-serif'],
        FontAwesome: ['FontAwesome'],
      },        
    },
  },
  variants: {
    extend: {},
    scrollbar: ['dark'],
  },
  plugins: [
    require('tailwind-scrollbar'),    
  ],
}
